"$schema" = 'https://starship.rs/config-schema.json'

palette = "solarized_light"

format = "$username$hostname$directory$git_branch$git_state$cmd_duration$line_break$character"
right_format = "$time"

[palettes.solarized_light]
base01 = "#586e75"
yellow = "#b58900"
red = "#dc322f"
magenta = "#d33682"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"

[character]
success_symbol = "[❯](red)[❯](yellow)[❯](green)"
error_symbol = "[❯](red)[❯](yellow)[❯](red)"
vimcmd_symbol = "[❮](green)[❮](yellow)[❮](red)"

[directory]
style = "bold blue"
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style) "

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold green"

[git_state]
format = "[$state( $progress_current/$progress_total)]($style) "
style = "bold yellow"

[cmd_duration]
min_time = 2_000
format = "took [$duration](yellow) "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
style = "base01"
