export PATH="$HOME/.local/bin:$PATH"
export ZSH="$HOME/.oh-my-zsh"
export HOMEBREW_NO_ANALYTICS=1

ZSH_THEME="robbyrussell"

plugins=(git)
while read -r repo; do
  [[ -n "$repo" ]] && plugins+=("${repo:t}")
done < "$HOME/dotfiles/zsh/plugins.txt"

source $ZSH/oh-my-zsh.sh
